#include <SDL3/SDL.h>

#define R_EV_QUIT            SDL_EVENT_QUIT
#define R_EV_KEYUP           SDL_EVENT_KEY_UP
#define R_EV_KEYDOWN         SDL_EVENT_KEY_DOWN
#define R_EV_MOUSEMOTION     SDL_EVENT_MOUSE_MOTION
#define R_EV_MOUSEBUTTONUP   SDL_EVENT_MOUSE_BUTTON_UP
#define R_EV_MOUSEBUTTONDOWN SDL_EVENT_MOUSE_BUTTON_DOWN
#define R_EV_MOUSEWHEEL      SDL_EVENT_MOUSE_WHEEL
#define R_EV_TEXTINPUT       SDL_EVENT_TEXT_INPUT

static const char r_key_map[256] = {
  [ SDL_SCANCODE_LSHIFT ]    = MU_KEY_SHIFT,
  [ SDL_SCANCODE_RSHIFT ]    = MU_KEY_SHIFT,
  [ SDL_SCANCODE_LCTRL ]     = MU_KEY_CTRL,
  [ SDL_SCANCODE_RCTRL ]     = MU_KEY_CTRL,
  [ SDL_SCANCODE_LALT ]      = MU_KEY_ALT,
  [ SDL_SCANCODE_RALT ]      = MU_KEY_ALT,
  [ SDL_SCANCODE_RETURN ]    = MU_KEY_RETURN,
  [ SDL_SCANCODE_BACKSPACE ] = MU_KEY_BACKSPACE,
};
