#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ncurses.h>

typedef struct {
    const char *name;
    int *value;
    int min, max;
} ConfigInt;

#define CMD_BAR_LEN 64
#define PREFIX_LEN 256
#define CC_LEN 64

int main(void) {
    // Default values (should match microui.h defaults)
    int MU_COMMANDLIST_SIZE     = 256 * 1024;
    int MU_ROOTLIST_SIZE        = 32;
    int MU_CONTAINERSTACK_SIZE  = 32;
    int MU_CLIPSTACK_SIZE       = 32;
    int MU_IDSTACK_SIZE         = 32;
    int MU_LAYOUTSTACK_SIZE     = 16;
    int MU_CONTAINERPOOL_SIZE   = 48;
    int MU_TREENODEPOOL_SIZE    = 48;
    int MU_MAX_WIDTHS           = 16;

    char prefix[PREFIX_LEN] = "/usr/local/microui";
    char cc[CC_LEN] = "gcc";

    ConfigInt config_ints[] = {
        {"MU_COMMANDLIST_SIZE",    &MU_COMMANDLIST_SIZE,    1024, 1024*1024},
        {"MU_ROOTLIST_SIZE",       &MU_ROOTLIST_SIZE,       1, 256},
        {"MU_CONTAINERSTACK_SIZE", &MU_CONTAINERSTACK_SIZE, 1, 256},
        {"MU_CLIPSTACK_SIZE",      &MU_CLIPSTACK_SIZE,      1, 256},
        {"MU_IDSTACK_SIZE",        &MU_IDSTACK_SIZE,        1, 256},
        {"MU_LAYOUTSTACK_SIZE",    &MU_LAYOUTSTACK_SIZE,    1, 256},
        {"MU_CONTAINERPOOL_SIZE",  &MU_CONTAINERPOOL_SIZE,  1, 256},
        {"MU_TREENODEPOOL_SIZE",   &MU_TREENODEPOOL_SIZE,   1, 256},
        {"MU_MAX_WIDTHS",          &MU_MAX_WIDTHS,          1, 64},
    };
    int num_config_ints = sizeof(config_ints)/sizeof(config_ints[0]);

    initscr();
    cbreak();
    noecho();
    keypad(stdscr, TRUE);

    int selected = 0;
    char status[128] = "Use arrows to move, +/- to change, s to save, q to quit, : for command bar, p to edit prefix, c to edit compiler.";
    char cmd_bar[CMD_BAR_LEN] = "";
    int cmd_mode = 0;
    int cmd_pos = 0;
    int prefix_mode = 0;
    int prefix_pos = strlen(prefix);
    int cc_mode = 0;
    int cc_pos = strlen(cc);

    while (1) {
        clear();
        mvprintw(0, 2, "Microui Configurator");
        mvprintw(1, 2, "----------------------------------------");
        mvprintw(2, 2, "Prefix (install path): %s", prefix);
        mvprintw(3, 2, "Compiler (CC): %s", cc);
        if (prefix_mode) {
            move(2, 26 + prefix_pos);
            curs_set(1);
        } else if (cc_mode) {
            move(3, 16 + cc_pos);
            curs_set(1);
        }
        for (int i = 0; i < num_config_ints; ++i) {
            if (i == selected && !prefix_mode && !cc_mode) attron(A_REVERSE);
            mvprintw(5 + i, 4, "%-22s [%d] (min:%d max:%d)", config_ints[i].name, *config_ints[i].value, config_ints[i].min, config_ints[i].max);
            if (i == selected && !prefix_mode && !cc_mode) attroff(A_REVERSE);
        }
        mvprintw(6 + num_config_ints, 2, "%s", status);

        // Draw command bar
        int y, x;
        getmaxyx(stdscr, y, x);
        mvhline(y-2, 0, ' ', x);
        if (cmd_mode) {
            mvprintw(y-2, 2, "Command: %s", cmd_bar);
            move(y-2, 10 + cmd_pos); // place cursor after "Command: "
            curs_set(1);
        } else if (!prefix_mode && !cc_mode) {
            mvprintw(y-2, 2, "Press ':' for command bar, 'p' to edit prefix, 'c' to edit compiler");
            curs_set(0);
        }
        refresh();

        int ch = getch();
        if (cmd_mode) {
            if (ch == 27) { // ESC to exit command mode
                cmd_mode = 0;
                cmd_bar[0] = 0;
                cmd_pos = 0;
            } else if (ch == KEY_BACKSPACE || ch == 127 || ch == '\b') {
                if (cmd_pos > 0) {
                    cmd_bar[--cmd_pos] = 0;
                }
            } else if (ch == '\n' || ch == '\r') {
                // Process command
                if (strcmp(cmd_bar, "quit") == 0) {
                    break;
                } else if (strcmp(cmd_bar, "export") == 0) {
                    FILE *f = fopen("microui_config.h", "w");
                    if (f) {
                        fprintf(f, "// Generated by microui-configurator (ncurses)\n");
                        fprintf(f, "#define MICROUI_PREFIX \"%s\"\n", prefix);
                        fprintf(f, "#define MICROUI_CC \"%s\"\n", cc);
                        for (int i = 0; i < num_config_ints; ++i) {
                            fprintf(f, "#define %s %d\n", config_ints[i].name, *config_ints[i].value);
                        }
                        fclose(f);
                        snprintf(status, sizeof(status), "Exported to microui_config.h!");
                    } else {
                        snprintf(status, sizeof(status), "Failed to write microui_config.h!");
                    }
                } else {
                    snprintf(status, sizeof(status), "Unknown command: %s", cmd_bar);
                }
                cmd_mode = 0;
                cmd_bar[0] = 0;
                cmd_pos = 0;
            } else if (cmd_pos < CMD_BAR_LEN-1 && ch >= 32 && ch <= 126) {
                cmd_bar[cmd_pos++] = (char)ch;
                cmd_bar[cmd_pos] = 0;
            }
            continue;
        }

        if (prefix_mode) {
            if (ch == 27) { // ESC to exit prefix edit
                prefix_mode = 0;
            } else if (ch == KEY_BACKSPACE || ch == 127 || ch == '\b') {
                if (prefix_pos > 0) {
                    prefix[--prefix_pos] = 0;
                }
            } else if (ch == '\n' || ch == '\r') {
                prefix_mode = 0;
            } else if (prefix_pos < PREFIX_LEN-1 && ch >= 32 && ch <= 126) {
                prefix[prefix_pos++] = (char)ch;
                prefix[prefix_pos] = 0;
            }
            continue;
        }

        if (cc_mode) {
            if (ch == 27) { // ESC to exit cc edit
                cc_mode = 0;
            } else if (ch == KEY_BACKSPACE || ch == 127 || ch == '\b') {
                if (cc_pos > 0) {
                    cc[--cc_pos] = 0;
                }
            } else if (ch == '\n' || ch == '\r') {
                cc_mode = 0;
            } else if (cc_pos < CC_LEN-1 && ch >= 32 && ch <= 126) {
                cc[cc_pos++] = (char)ch;
                cc[cc_pos] = 0;
            }
            continue;
        }

        if (ch == 'q') break;
        else if (ch == KEY_UP)    { if (selected > 0) selected--; }
        else if (ch == KEY_DOWN)  { if (selected < num_config_ints-1) selected++; }
        else if (ch == '+' || ch == '=') {
            if (*config_ints[selected].value < config_ints[selected].max)
                (*config_ints[selected].value)++;
        }
        else if (ch == '-' || ch == '_') {
            if (*config_ints[selected].value > config_ints[selected].min)
                (*config_ints[selected].value)--;
        }
        else if (ch == 's') {
            FILE *f = fopen("microui_config.h", "w");
            if (f) {
                fprintf(f, "// Generated by microui-configurator (ncurses)\n");
                fprintf(f, "#define MICROUI_PREFIX \"%s\"\n", prefix);
                fprintf(f, "#define MICROUI_CC \"%s\"\n", cc);
                for (int i = 0; i < num_config_ints; ++i) {
                    fprintf(f, "#define %s %d\n", config_ints[i].name, *config_ints[i].value);
                }
                fclose(f);
                snprintf(status, sizeof(status), "Exported to microui_config.h!");
            } else {
                snprintf(status, sizeof(status), "Failed to write microui_config.h!");
            }
        }
        else if (ch == ':') {
            cmd_mode = 1;
            cmd_bar[0] = 0;
            cmd_pos = 0;
        }
        else if (ch == 'p') {
            prefix_mode = 1;
            prefix_pos = strlen(prefix);
        }
        else if (ch == 'c') {
            cc_mode = 1;
            cc_pos = strlen(cc);
        }
    }

    endwin();
    return 0;
}
/*
Compile with:
gcc microui-config.c -lncurses -o microui-config
*/

